"""empty message

Revision ID: 003bb97751e8
Revises: e3b6af5b019a
Create Date: 2019-01-29 20:02:02.380142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '003bb97751e8'
down_revision = 'e3b6af5b019a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_comment', sa.Column('food_ids', sa.String(length=200), nullable=False, comment='商品ID'))
    op.drop_constraint('member_comment_ibfk_3', 'member_comment', type_='foreignkey')
    op.drop_column('member_comment', 'food_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_comment', sa.Column('food_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='商品ID'))
    op.create_foreign_key('member_comment_ibfk_3', 'member_comment', 'food', ['food_id'], ['id'])
    op.drop_column('member_comment', 'food_ids')
    # ### end Alembic commands ###
