"""empty message

Revision ID: 2c4720d60296
Revises: c69cf85a5f34
Create Date: 2019-01-28 16:29:30.805833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4720d60296'
down_revision = 'c69cf85a5f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('pay_time', sa.Integer(), nullable=False, comment='会员支付到账时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'pay_time')
    # ### end Alembic commands ###
