"""empty message

Revision ID: 365457c8fbd4
Revises: 401727cba1c3
Create Date: 2019-01-29 11:42:17.238221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '365457c8fbd4'
down_revision = '401727cba1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_comment', 'food_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_comment', sa.Column('food_ids', mysql.VARCHAR(length=200), nullable=False, comment='食物IDs'))
    # ### end Alembic commands ###
