"""empty message

Revision ID: 401727cba1c3
Revises: d3b9dd9951aa
Create Date: 2019-01-29 11:17:22.975172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401727cba1c3'
down_revision = 'd3b9dd9951aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_comment', sa.Column('score', sa.SmallInteger(), nullable=True, comment='评分'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_comment', 'score')
    # ### end Alembic commands ###
