"""empty message

Revision ID: 70b575da3ec4
Revises: 9dc3838d34b5
Create Date: 2019-01-24 16:34:23.743933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70b575da3ec4'
down_revision = '9dc3838d34b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('name', mysql.VARCHAR(length=30), nullable=True, comment='name'))
    # ### end Alembic commands ###
