"""empty message

Revision ID: a61178aafb4c
Revises: 
Create Date: 2019-01-24 16:29:42.696022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a61178aafb4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_client', 'client_type',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True,
               existing_comment='客户端类型: 1, 微信小程序(目前); 2, qq;')
    op.alter_column('member_client', 'openid',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True,
               existing_comment='第三方ID, 小程序openid(目前)')
    op.create_foreign_key(None, 'order', 'member', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.alter_column('member_client', 'openid',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False,
               existing_comment='第三方ID, 小程序openid(目前)')
    op.alter_column('member_client', 'client_type',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False,
               existing_comment='客户端类型: 1, 微信小程序(目前); 2, qq;')
    # ### end Alembic commands ###
