"""empty message

Revision ID: c69cf85a5f34
Revises: 4cb7b2c90027
Create Date: 2019-01-27 15:40:18.605876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c69cf85a5f34'
down_revision = '4cb7b2c90027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_site', sa.Column('all_member_count', sa.Integer(), nullable=False, comment='会员总数'))
    op.add_column('stat_daily_site', sa.Column('member_count', sa.Integer(), nullable=False, comment='当日会员总数'))
    op.add_column('stat_daily_site', sa.Column('money', sa.DECIMAL(), nullable=False, comment='当日应收总金额'))
    op.add_column('stat_daily_site', sa.Column('order_count', sa.Integer(), nullable=False, comment='当日订单总数'))
    op.add_column('stat_daily_site', sa.Column('share_count', sa.Integer(), nullable=False, comment='当日分享总数'))
    op.drop_column('stat_daily_site', 'total_order_count')
    op.drop_column('stat_daily_site', 'total_share_count')
    op.drop_column('stat_daily_site', 'total_money')
    op.drop_column('stat_daily_site', 'total_member_count')
    op.drop_column('stat_daily_site', 'total_new_member_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_site', sa.Column('total_new_member_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='当日新增会员总数'))
    op.add_column('stat_daily_site', sa.Column('total_member_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='当日会员总数'))
    op.add_column('stat_daily_site', sa.Column('total_money', mysql.DECIMAL(precision=10, scale=0), nullable=False, comment='当日应收总金额'))
    op.add_column('stat_daily_site', sa.Column('total_share_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='当日分享总数'))
    op.add_column('stat_daily_site', sa.Column('total_order_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='当日订单总数'))
    op.drop_column('stat_daily_site', 'share_count')
    op.drop_column('stat_daily_site', 'order_count')
    op.drop_column('stat_daily_site', 'money')
    op.drop_column('stat_daily_site', 'member_count')
    op.drop_column('stat_daily_site', 'all_member_count')
    # ### end Alembic commands ###
