"""empty message

Revision ID: cde97c370308
Revises: b6d9fb24ca94
Create Date: 2019-01-26 20:59:58.013588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cde97c370308'
down_revision = 'b6d9fb24ca94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat_daily_food', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_food', sa.Column('date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='统计日期'))
    # ### end Alembic commands ###
