"""empty message

Revision ID: d1c36eb15446
Revises: 70b575da3ec4
Create Date: 2019-01-25 10:44:59.100104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1c36eb15446'
down_revision = '70b575da3ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue', 'data',
               existing_type=mysql.VARCHAR(length=500),
               comment='队列数据',
               existing_nullable=False)
    op.alter_column('queue', 'name',
               existing_type=mysql.VARCHAR(length=30),
               comment='队列名',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue', 'name',
               existing_type=mysql.VARCHAR(length=30),
               comment=None,
               existing_comment='队列名',
               existing_nullable=False)
    op.alter_column('queue', 'data',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='队列数据',
               existing_nullable=False)
    # ### end Alembic commands ###
