"""empty message

Revision ID: dee6a1e2a10a
Revises: 003bb97751e8
Create Date: 2019-01-30 21:14:59.161875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dee6a1e2a10a'
down_revision = '003bb97751e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_sale_change_log', sa.Column('total_price', sa.DECIMAL(), nullable=False, comment='售卖金额'))
    op.drop_column('food_sale_change_log', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_sale_change_log', sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=False, comment='售卖金额'))
    op.drop_column('food_sale_change_log', 'total_price')
    # ### end Alembic commands ###
