"""empty message

Revision ID: e00af350376d
Revises: cde97c370308
Create Date: 2019-01-26 21:00:55.778864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e00af350376d'
down_revision = 'cde97c370308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat_daily_member', 'date')
    op.drop_column('stat_daily_site', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_site', sa.Column('date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='统计日期'))
    op.add_column('stat_daily_member', sa.Column('date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='统计日期'))
    # ### end Alembic commands ###
