"""empty message

Revision ID: e3b6af5b019a
Revises: 365457c8fbd4
Create Date: 2019-01-29 19:47:59.139842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b6af5b019a'
down_revision = '365457c8fbd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_comment', sa.Column('food_id', sa.Integer(), nullable=False, comment='商品ID'))
    op.create_foreign_key(None, 'member_comment', 'food', ['food_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_comment', type_='foreignkey')
    op.drop_column('member_comment', 'food_id')
    # ### end Alembic commands ###
